"""Pydantic model for article text generated by or sent to OpenAI workflows."""

import json
from pathlib import Path
from typing import Any, ClassVar

from pydantic import BaseModel, Field


class Article(BaseModel):
    """Article text fields used for prompting and extraction."""

    Headline: str = Field(description="Headline of the article")
    Subheadline: str = Field(description="Subheadline of the article")
    Paragraphs: str = Field(description="Paragraphs of the article")


class ArticleCorpus(BaseModel):
    """A collection of article records containing only text fields."""

    Article: ClassVar[type[Article]] = Article
    articles: list[Article]


def read_json_to_article_corpus(json_path: str) -> ArticleCorpus:
    """
    Read the JSON file containing the articles and return the ArticleCorpus object containing the articles.
    The headline, subheadline, and paragraphs are required for each article in the JSON file.
    """
    all_articles: ArticleCorpus = ArticleCorpus(articles=[])
    with Path(json_path).open("r", encoding="utf-8") as file:
        articles = json.load(file)

        if isinstance(articles, dict):
            article_records: list[dict[str, Any]] = list(articles.values())
        else:
            article_records = articles

        for article in article_records:
            article_obj = Article(
                Headline=article["headline"],
                Subheadline=article["subheadline"],
                Paragraphs=article["paragraphs"],
            )
            all_articles.articles.append(article_obj)

    return all_articles
