"""Pydantic model for article text generated by or sent to OpenAI workflows."""

from pydantic import BaseModel, Field


class ArticleCorpus(BaseModel):
    """A collection of article records containing only text fields."""

    class Article(BaseModel):
        """Article text fields used for prompting and extraction."""

        Headline: str = Field(description="Headline of the article")
        Subheadline: str = Field(description="Subheadline of the article")
        Paragraphs: str = Field(description="Paragraphs of the article")

    articles: list[Article]


def read_json_to_article_corpus(json_path: str) -> ArticleCorpus:
    """
    Read the JSON file containing the articles and return the ArticleCorpus object containing the articles.
    The headline, subheadline, and paragraphs are required for each article in the JSON file.
    """
    all_articles: ArticleCorpus = ArticleCorpus(articles=[])
    with open(json_path, "r") as file:
        articles = json.load(file)
        for article in articles:
            article_obj = Article(
                Headline=article["headline"],
                Subheadline=article["subheadline"],
                Paragraphs=article["paragraphs"],
            )
            all_articles.articles.append(article_obj)

    return all_articles
